### ISSUE TITLE
溫室氣體排放資料（環保署）重新確認

### ISSUE THREAD

**Issue by qyke** [gcaa-org-tw/thaubing-esg#114]
### 問題描述

> 使用者來信，
> 
> 日前我們在參照ESG檢測儀的數據時，發現許多企業於2017年的「直接＋間接排放」欄位的排放數據（從左邊數過來第三欄），明顯偏離五年來的趨勢。下表是我從ESG檢測儀整理的國內主要溫室氣體排放企業的數據：
> 
> ![螢幕擷取畫面 (699)](https://user-images.githubusercontent.com/68453922/174525544-bae23ef0-50c9-4535-aff3-a88e0233fa99.png)
> 
> 以中鋼為例，其GHG在2016年的排放量達八位數(22,337,642.14)Co2e，2017掉到六位數，到2018年又回到了八位數。台積電的數據也是在2017年銳減，並不符合逐年成長的趨勢。下圖是我把2017年的資訊，單獨抽換成溫室氣體申報平台(排放量單筆查詢後加總)的數據，就比較符合各企業五年來的變動趨勢了：
> 
> ![螢幕擷取畫面 (700)](https://user-images.githubusercontent.com/68453922/174525560-87173cc0-13b7-49e3-a92a-3aef40b646df.png)
> 
> 自此，敬請貴聯盟抽空確認，ESG檢測儀中，每間企業2017年「直接＋間接排放」欄位的數字（從左邊數過來第三欄），有沒有錯置、誤植的可能性。

### 系統資訊

無

### 問題產生的步驟

無

### 補充資訊

經確認手上的資料檔與前台呈現，確實有數據差異
![image](https://user-images.githubusercontent.com/68453922/174526081-c28790e9-d331-454e-9c87-fb3d80e5dcdc.png)

![image](https://user-images.githubusercontent.com/68453922/174526153-cb11fd38-2b24-47b0-bd80-55f95dfec568.png)

麻煩ddio再確認一下數據抓取時，是不是有抓錯格或者加總錯誤。

**Comment by ddio** [comment]
## 錯誤原因：

原本的j溫室氣體資料（`data/ghg_p_01.csv`）中，有 98 筆的重複資料，推測是當初下載錯誤，或是當時開放資料平台的資料有誤。

- 錯誤資料請見： [溫室氣體重複項目.txt](https://github.com/gcaa-org-tw/thaubing-esg/files/9027680/default.txt)
- 所有重複的資料，皆為 106 年，推測應是當初合併資料時，106 的資料就是錯的

已更新至最新版，並確認無資料重複的問題。

- 中鋼頁面： https://thaubing-esg.gcaa.org.tw/company/30414175/
- 溫室氣體截圖：
  > ![2022-07-01 17-25-35 的螢幕擷圖](https://user-images.githubusercontent.com/271157/176867157-71e3b23d-6e68-4000-9997-ab4cb3659975.png)
