### ISSUE TITLE
凌陽科技來信_溫室氣體排放資料誤植

### ISSUE THREAD

**Issue by qyke** [gcaa-org-tw/thaubing-esg#116]
### 問題描述

在透明足跡-【ESG檢測儀】中，本公司的溫室氣體排放量誤植，2020年本公司為4,056.327噸CO2e，(肆仟零伍拾陸點參貳柒)；
貴網誤將4056.327的”,”及”.”均視為”,”，造成排放量變成4百多萬噸。
惠請協助更正，以免造成誤會與誤導。

### 系統資訊

- 無

### 問題產生的步驟

無

### 修正方式

已更新[原始大表](https://docs.google.com/spreadsheets/d/1jFmBLsT7ctkQ4fl-sfNrZiyJap5gIOTOeB47Ew8rFdM/edit?usp=sharing)

資訊修正如下
2401	凌陽科技股份有限公司　範疇二（值）　4,056.327

**Comment by qyke** [comment]
這個要優先處理～因為對方企業已經寄了多次信來了～

**Comment by ddio** [comment]
更新完畢，另外，順便加了一支機器人，每天早上五點，會重新跑一次原始大表，只要在那之前改上去的數據，五點後就會自動更新到網站上～
