### ISSUE TITLE
超豐電子、南寶樹脂_溫室氣體排放資料誤植

### ISSUE THREAD

**Issue by qyke** [gcaa-org-tw/thaubing-esg#117]
### 問題描述

半導體業，超豐電子，在檢查資料時發現，在 溫室氣體排放 範疇一（值） 的部分，數字有錯。
應修正為：
2020－793.4422
～
化學工業，南寶樹脂，在檢查資料時發現，在 溫室氣體排放 範疇一（值）、範疇二（值）  的部分，數字有錯。
三個年度的資料都要修改，分別為
範疇一
2018－6.923
2019－5.570
2020－5.068
～
範疇二
2018－7.601
2019－8.494
2020－8.308

### 系統資訊

- 無

### 問題產生的步驟

無

### 修正方式

已更新[原始大表_超豐](https://docs.google.com/spreadsheets/d/1jFmBLsT7ctkQ4fl-sfNrZiyJap5gIOTOeB47Ew8rFdM/edit?usp=sharing)

已更新[原始大表_南寶](https://docs.google.com/spreadsheets/d/1KyPOaHnIn9SAmWzOQAvDpKhRpHEdl2dUSjtxaMSkI9s/edit?usp=sharing)

**Comment by ddio** [comment]
更新完畢，另外，順便加了一支機器人，每天早上五點，會重新跑一次原始大表，只要在那之前改上去的數據，五點後就會自動更新到網站上～
