### ISSUE TITLE
溫室氣體年排放量_計算

### ISSUE THREAD

**Issue by qyke** [gcaa-org-tw/thaubing-esg#121]
## 工作項目

將溫室氣體資料整理計算
資料集：[溫室氣體年排放量](https://data.epa.gov.tw/dataset/detail/GHG_P_01) 

- 欄位使用
  - App_year(監測年度)、companyno(事業編號)、companyname(公私場所名稱)、ccksicco1(行業別代碼)、Tot2(間接排放量（公噸CO2e）)、tot(排放總量（公噸CO2e）)。
- 資料區間
  - 圖表僅使用
    1. cause(自願揭露或法規規定)為：［依法申報］的值
        > 僅會保留102年後的資料
    2. ccksicco1(行業別代碼)移除［3510（電力供應業）］不計
- 資料取得
  - [ ] 資料集取得（更新後台既存資料）
  - [ ] 計算Tot1(直接排放量（公噸CO2e）)［算法：tot - Tot2］
  - [ ] 依App_year(監測年度)、companyno(事業編號)加總Tot1、Tot2、tot
  - [ ] 公司名稱保留最新年度的值（可直接以公司清單的公司名即可）
- 基準、BAU計算
  - [ ] 以2019為基準值（100%），計算各年度差值（%）
    > 若2019為空值，則不呈現於前台
  - [ ] 計算2017～2020的移動平均值做為BAU趨勢線的依據
    > 若2017或2020有缺值，則區段往前位移為2016～2019
- 產業別計算
  - [ ] 依據上市櫃公司清單給定產業別進行加總計算，計算方式與上述相同
  - [ ] 同樣以2019為基準，並計算BAU
- 呈現相關工作如下：
  - #126 
  - #127
  - #128
  - #131

### 說明／補充／備註
呈現時，須將[淨零路徑](https://docs.google.com/spreadsheets/d/1c6i74AmOziVfr8iN_UPlcTia-deKS6PLL8_8M3nEWww/edit?usp=sharing)做成區域圖放在底部

**Comment by ddio** [comment]
@qyke , 這批資料，要怎麼成現在網頁上呢？

**Comment by ddio** [comment]
BAU 完工～～

1. 公司範例可見[茂矽](https://github.com/gcaa-org-tw/thaubing-esg/blob/main/esg-ui/static/content/company/%E8%8C%82%E7%9F%BD-bau.csv)
2. 和試算表不同的是，BAU 最小值為 0 ，不會是負數，例如[統懋](https://github.com/gcaa-org-tw/thaubing-esg/blob/main/esg-ui/static/content/company/%E7%B5%B1%E6%87%8B-bau.csv)
3. 產業範例可見[半導體業](https://github.com/gcaa-org-tw/thaubing-esg/blob/main/esg-ui/static/content/industry/26-bau.csv)
4. 各產業統計，因為每間公司有資料的年份不一致，不確定這樣是否合理，但總之[結果可以看這兒](https://github.com/gcaa-org-tw/thaubing-esg/blob/main/esg-ui/static/content/overview/bau.csv)
