### ISSUE TITLE
首頁_版面調整

### ISSUE THREAD

**Issue by qyke** [gcaa-org-tw/thaubing-esg#125]
### 工作項目
主要統整目前ESG檢測儀首頁上面的細節調整
淨零路徑模擬器的切換與篩選機制也在這邊處理

本次使用的[Figma](https://www.figma.com/file/rpSC4798yFBjlI8SLLcrLz/ESG-%E6%AA%A2%E6%B8%AC%E5%84%80?node-id=819%3A701)
總統盃[討論紀錄](https://docs.google.com/document/d/1TTISVjeZA9w9Fjf7op8FVi4IQlbrNR4iuR0oso15syQ/edit?usp=sharing)

#### 新增項目：
- [x] 新增切換標籤
- [x] 新增捐款按鈕
- [ ] #157
- [ ] #158

#### 調整項目：
- [x] 碳密集度欄位的長條圖先關閉（原因為目前的算法無法確實反映企業碳密集度的變化）
- ~~[ ] 折線圖的圖表刻度太精細，導致波動不大的數值看起來差異很大~~

### 說明／補充／備註

**Comment by ddio** [comment]
@qyke , 

進階篩選功能是什麼？印象中沒討論過這件事，Figma 上好像也沒有？

**Comment by ddio** [comment]
@qyke ,

捐款連結，需要放 utm 嗎？

**Comment by qyke** [comment]
捐款連結請用這個
https://gcaa.neticrm.tw/civicrm/contribute/transact?reset=1&id=41&utm_source=Web&utm_content=ESG_donate&utm_campaign=TB3
上下都放一樣的就好，不用特別區分。

**Comment by ddio** [comment]
@qyke ,

調整項目的那兩項（碳密集度欄位的長條圖先關閉、折線圖的圖表刻度太精細，導致波動不大的數值看起來差異很大），可以提供範例截圖嗎？我假設這裡的「首頁」，是指 [ESG 資料庫的產業頁面](https://thaubing-esg.gcaa.org.tw/industry/03/)，但這頁沒有折線圖，但如果說的是公司頁面的話，又沒有碳密集度欄位，我怕我改錯地方。

**Comment by qyke** [comment]
拍謝～
調整這邊寫得不夠明確。
～
碳密集度的部分是指首頁。
![image](https://user-images.githubusercontent.com/68453922/184799361-adca68e1-f9ba-40e5-859e-663d88d08756.png)
先前跟家緯討論後，覺得這樣放可能會有誤讀，所以麻煩你先關起來。
～
折線圖的部分，我重新確認過，看起來不太容易改，先不做調整。
不容易改的原因是，每一家公司的折線圖的刻度都不相同，看起來不容易以相等的刻度來處理。
所以這部分先擱置。

**Comment by qyke** [comment]
有兩個問題提出，先記著

1. 在公司頁面，CSR報告來的，範疇一、二、三，目前看起來並沒有依照一二三的順序來呈現。

![image](https://user-images.githubusercontent.com/68453922/184800452-e9becaae-1992-4287-9251-f0572c3da178.png)

目前是一、三、二
依照一般在看溫室氣體排放的方式，應該由上到下，以三、二、一來排比較好
～
2. 產業別選單這邊，出現了好多的重複產業，有的點下去是無效的連結，不太確定是哪邊動到了？

**Comment by ddio** [comment]
@qyke , 

Github ticket 的習慣用法是，盡量讓每張 ticket 都是一個「可執行，可以訂完成時間，而且不會做太久」的工作，這樣的好處是：

1. ticket 不會越開越多，但舊的一直關不掉，最後因為太亂，造成大家放棄使用 ticket 來管理工作
2. 可以計量的 ticket ，才可以既量工作總量
3. 減輕人腦負擔，因為一張票就是對應一件固定的工作或目標，不會變化，不用當連載一直追

所以：

1. 如果有原本沒規劃到，開工後才衍伸的相關工作，建議開其他票，這樣這張票才有做完的一天
2. 如果是原本想做，但目前還做不了（例如還沒設計、還需要討論、還不夠具體），也可以開另外一張票，並用 `#<ticket_id>` ，在這張票裡提到它，就能建立關聯

**Comment by ddio** [comment]
@qyke , 

已將還沒做，但還不確定要做什麼的事情，轉為新的票，這張票已經沒有待做了～

**Comment by ddio** [comment]
發現漏了碳密集度～
