### ISSUE TITLE
首頁_歷年碳排變化+目標減量_依產業別

### ISSUE THREAD

**Issue by qyke** [gcaa-org-tw/thaubing-esg#127]
### 工作項目
圖表呈現碳排放變化量 + 企業自訂減量目標
依產業別顯示

- [x] 底圖為兩條淨零路徑的區域圖（IPCC、PNNL）
- [x] 歷年碳排放量以2019年為基準
- [x] 預設呈現五家公司（總排放量最高的五家）
- [x] 圖表上同時呈現既有碳排變化、企業自訂目標線
- [x] 增減寫法為 紅字［較基準上升或持平］；黑字［介於下降至IPCC間］；綠字［下降較IPCC多］
- [x] 浮動標籤上一次呈現一家公司
- [x] 跨圖表同時呈現BAU、目標值
- [x] 年份採拉動方式呈現，預設呈現10年（再請ddio參考線稿設計）
- [x] 圖表起始為：2013；結束為：2050
- [x] 手機板版面再麻煩ddio協助

### 說明／補充／備註
使用資料：[溫室氣體年排放量_計算](https://github.com/gcaa-org-tw/thaubing-esg/issues/121)

**Comment by qyke** [comment]
目標可用的清單提供如下
[溫室氣體公司減碳目標整理_0816](https://docs.google.com/spreadsheets/d/1MWuY0UNQS-0O-ogelG81Vfh7AAeqrxynKPAnPjRH-qs/edit?usp=sharing)
～
操作方式說明：

- base_year為原本公司設定的基準年，需要統一換算為2019作為基準
- 各年度的%是相較基準年的排碳量
- 換算基準年的計算方式為（各年度實際排放量 / 基準年排放量）X 100%
- 如果換算上有什麼問題，再提出討論～

**Comment by ddio** [comment]
@qyke , 

關於**基準年的計算方式**，可以舉個實例嗎？我不確定規則裡的「基準年的計算方式」是什麼。

**Comment by qyke** [comment]
sorry，稍早在處理其他事情。
沒有把需求跟做法講清楚，很抱歉QQ
～
1. 基準年計算方式，我寫在[這份的第二個工作表中](https://docs.google.com/spreadsheets/d/1MWuY0UNQS-0O-ogelG81Vfh7AAeqrxynKPAnPjRH-qs/edit?usp=sharing)，再麻煩你確認一下～
2. 資料點跟線段的舉例說明如下：
假設A公司提出了2030、2035、2050三個年度的目標，則在圖上，可以畫出三個線段（最新的排放值到2030、2030到2035、2035到2050）；加上三個資料點（2030、2035、2050）
B公司只提出2030的目標，則在圖上就只畫出一個線段（最新的排放值到2030），後面不畫；資料點也只有一個2030
C公司提出2025、2050的目標，則會畫出兩個線段（最新的排放值到2025、2025到2050）；加上兩個資料點（2025、2050）
目標因為還是以具體的年度承諾為主，就不會像BAU那樣有每年的推估變化值（沒有不能算，只是不符合現實）
所以在跨圖表的對應上，也僅有這幾個特定年份會有跨圖表的值可做比較。

**Comment by ddio** [comment]
但之前討論圖表時，有說要能逐年對照每間公司的 BAU vs 承諾 XD

所以可以內插的，應該事要逐年算？不然就是 tooltip 不能逐年顯示公司承諾。

![2022-08-16 23-00-59 的螢幕擷圖](https://user-images.githubusercontent.com/271157/184912662-c51d06d2-6f00-4d5a-b831-7049a00fa86a.png)

**Comment by qyke** [comment]
!!!
拍謝，我遺漏了這個部分。
這樣的話，就還是要麻煩ddio用逐年的推估值把每一年的降幅算出來，然後畫上去。
～
針對明確的承諾年份，我這邊再請kelvin協助設計明確的標記，讓目標排放的推估值跟承諾值可以區分出來。

**Comment by ddio** [comment]
tooltip 、上下圖表連動的部份，待 08/18 討論後再處理～
