### ISSUE TITLE
各文字區塊撰寫

### ISSUE THREAD

**Issue by qyke** [gcaa-org-tw/thaubing-esg#129]
### 工作項目
再麻煩ddio開區塊文件給綠盟做填寫

#### 需要填寫的位置
- [x] BAU 頁面，新增企業分類：目標積極企業 （2030年減量目標最積極）
- [x] IPCC、PNNL 說明圖例
  - IPCC：聯合國政府間氣候變化專門委員會（IPCC）於氣候變遷第六次評估報告（AR6）指出，全球溫室氣體排放量以2019年為基準年，應於2030年減排43％、於2050年減排84％。本站圖表依IPCC目標於2019年-2030年、2030年-2050年兩個區間內，進行線性推估，得到區間內每一年度之目標值。
  - PNNL：綠色公民行動聯盟與美國西北太平洋實驗室（PNNL）合作，完成Low Emission Development Strategy for Taiwan研究報告。依據研究提出之模型，臺灣製造業以2019年為基準年，應於2030年減排50％，於2050年達成淨零碳排。本站圖表依PNNL製造業目標於2019年-2030年、2030年-2050年兩個區間內，進行線性推估，得到區間內每一年度之目標值。
- [x] BAU 頁面，標題「企業維持原狀的碳排成長」改為「企業溫室氣體年排放量趨勢與推估」
- [x] BAU 圖表下方說明
  - 基準年：用意是讓不同企業的減碳成效能夠有相同的比較基準。在淨零路徑模擬器將2019年為基準年，以符合聯合國政府間氣候變化專門委員會（IPCC）所訂定的基準。
  - 溫室氣體排放基線／一切照舊（Business As Usual, BAU）：所謂的BAU是「不採取任何溫室氣體減量作為下，各個溫室氣體排放源的排放變化。」淨零路徑模擬器的排放量推估方式為：近四年排放量變化均值。
- [x] 企業承諾圖表下方說明
  - 基準年：用意是讓不同企業的減碳成效能夠有相同的比較基準。在淨零路徑模擬器將2019年為基準年，以符合聯合國政府間氣候變化專門委員會（IPCC）所訂定的基準。
  - 企業目標：參照公開資訊觀測站－[溫室氣體排放及減量資訊](https://mops.twse.com.tw/mops/web/t152sb01)的資料，將企業的減碳目標規劃依2019做為基準年進行標準化處理後呈現。
- [x] 企業溫室氣體年排放量趨勢與淨零目標（公司頁圖）
  - 上述三者並列

**Comment by ddio** [comment]
@qyke , 

目前 Figma 只有安排一個欄位，可以說明圖上有標的各種東西。

![2022-08-11 09-27-18 的螢幕擷圖](https://user-images.githubusercontent.com/271157/184049722-1dd3680a-8fea-496d-9d81-90c12bf15a8d.png)

但從你貼的欄位來看，如果有篇比較長的文章完整說明，會比較符合目的，我們是否：

1. 先把你想寫的東西，寫在一份 google doc 上，這樣我比較知道該放成一篇獨立的，還是分成許多小段
2. 無論是否有一篇文整的文章，都該準備一份簡短說明，放在公司、產業的圖下方，可以包含連結至其他詳細說明的頁面

另外，我不太確定「公司名稱顯示文字」是什麼 XD

**Comment by ddio** [comment]
文案在這ㄦ：
https://docs.google.com/document/d/1zn8I0DNWVyTu7hPwYhtfQVSDbS6bIfw7815UnQnJvG0/edit
