### ISSUE TITLE
2022 總統杯圖表待做

### ISSUE THREAD

**Issue by ddio** [gcaa-org-tw/thaubing-esg#159]
### 工作項目

1. [x] 具體承諾的年份，以垂直線標注
2. [x] `bug` 修正有實際資料時，tooltip 的用字
8. [x] 以圖說 / legend 控制要強調的公司
7. [x] 點擊公司的線段後，跳到公司頁面

**Comment by qyke** [comment]
幾項BUG回報。

針對公司頁的圖表
1. 有幾家公司在公司頁面這邊沒有出現目標的線段，需要確認原因，並補上。
EX. [遠東新](https://thaubing-esg.gcaa.org.tw/company/03522600/)、[台化](https://thaubing-esg.gcaa.org.tw/company/58650902/)、[台塑](https://thaubing-esg.gcaa.org.tw/company/75708007/)
2. 即使沒有承諾淨零目標也需要顯示碳排的趨勢跟推估。
EX. [中龍](https://thaubing-esg.gcaa.org.tw/company/84613756/)、[榮成](https://thaubing-esg.gcaa.org.tw/company/34202841/)
3. 目前目標的線段呈現看起來還沒跟首頁這邊的統一，再麻煩ddio調整。

針對首頁的圖表－目標
1. 因應圖表資訊調整，目標這邊的Y軸上限改成120%，讓不同公司的目標差異更明顯。
2. 目標的起始點，2019年，依照標準年的概念，應該是大家都是從100%往下降，但目前看起來並不是同一點出發。
要麻煩ddio確認一下算法。我們在目標這邊，算法應該是都用CSR報告的資料來計算。
![image](https://user-images.githubusercontent.com/68453922/185781441-8f438658-6a46-41ab-ae99-59267f171cb3.png)
3. [水泥工業](https://thaubing-esg.gcaa.org.tw/net-zero/01?filter=top5)這邊的目標，目前應該只有幸福水泥有提出，但他的提法是每年相較基準年減10%，目前的畫法看不出來（只有2025年），不確定是什麼原因。

**Comment by ddio** [comment]
@qyke , `針對首頁的圖表－目標 - 第二點` ，按照公式，2019 不一定是 100% ，2019 也不一定會有值呦～

1. 2019 的 % = base_year_ems * [ `2019 前的那次承諾 %` + (`2019 後的那次承諾%` - `2019 前的那次承諾 %`) / (2019 - `base_year`)]
2. 如果沒有 `2019 前的那次承諾 %` ，例如 `base_year` > 2019 時，就不會有 2019 的 %

還是我需要把所有按照公式算好的 % ，都用 `2019 應該是 100%` ，重新正規化一次呢？

**Comment by qyke** [comment]
@ddio 
我有點看不懂你的公式QQ，但應該是要重新算過一次，讓2019年都是100%。
在目標這邊的算法，我們要做的是把不同公司依據不同基準年算出來的目標值，標準化為同一個基準年（2019）的目標降幅。這樣才能比較不同公司以相同的標準，每個目標年各承諾了多少的降幅。
所以在這邊應該是 [溫室氣體公司減碳目標整理_0819_更新](https://docs.google.com/spreadsheets/d/1MWuY0UNQS-0O-ogelG81Vfh7AAeqrxynKPAnPjRH-qs/edit?usp=sharing)
先以［base_year_ems］去乘上各家公司每個年度的排放，
然後以2019作為基準年，將每個年度的排放除以基準年排放值［2019_ems］得到每個目標年的降幅。
這樣計算上就會所有公司的2019是100%，其他年度則是相對於2019的降幅。
～
抱歉QQ，讓你要加班改。

**Comment by ddio** [comment]
@qyke  ，今天回報的幾個問題都修了，幸福水泥的部份，修正後，2025 開始會是一條水平線，如果和預期的不一樣，再討論。

**Comment by ddio** [comment]
剩下兩個工作也做完了～
