### ISSUE TITLE
首頁_企業目標圖表_修正資訊與呈現

### ISSUE THREAD

**Issue by qyke** [gcaa-org-tw/thaubing-esg#161]
### 工作項目
看了各產業的狀況之後，主要有幾個問題要修。
項目有點多，我依照調整的優先順位來寫。
有問題可隨時討論～

1. [ ] 目標要重算
   - 現況圖表看起來很怪，請看圖
     > ![image](https://user-images.githubusercontent.com/68453922/185580720-f3befd44-478d-4f0c-aff7-e07c53ab53d9.png)
     > ![image](https://user-images.githubusercontent.com/68453922/185580789-5ae4b434-58e8-457d-a68d-92521ed91d62.png)
   - 之所以會出現這種異常高值，原因是我們在目標同時使用了兩組數據，盤查&CSR報告
     在實際排放跟標準化的基準年，我們都使用了盤查的數據。
     但是在目標的換算，使用的是CSR報告的資料，但因為CSR報告的資料範疇與盤查不盡相同，所以會出現這種3倍或5倍的高值問題。
   - 解法是重算資料。
     我把[這一份](https://docs.google.com/spreadsheets/d/1MWuY0UNQS-0O-ogelG81Vfh7AAeqrxynKPAnPjRH-qs/edit?usp=sharing)用來算目標的檔案做了更新，加上了一個欄位［2019_ems］
     這個欄位同樣取自CSR報告，用同樣來源的基準年來算減碳幅度，就可以避免發生現況下圖表長得很怪的問題。
2. [ ] BAU與目標圖表連動問題
   - 解決了圖表的問題後，要處理的是圖表連動關係的部分。
     原本預期是上下兩張圖表可以跨圖表查閱，所以我們可以在上面直接比較BAU跟目標的值。但是到了下面目標這張圖，會出現一個問題，［除了目標年以外，都是我們線性推估的值］。在上面的圖表可以解釋為是要比較逐年降幅與目標降幅，但在下面以目標為主時，還是應該要以企業有具體承諾的年份來做顯示，若企業沒有承諾，用線性推估去說企業2023或2037年會降多少，還是有點怪。
   - 工作項目：上面BAU圖表不動。**下面目標圖表，只顯示從基準年起算的目標年降幅，中間一樣有線段連接，不顯示逐年的資料**，在tooltip比較上，下方圖表僅讓目標年可以顯示對比。
3. [ ] 目標線段畫線問題（需畫圖）
   - 延續上面的調整，在線段上，目標圖表改為從基準年（2019開始）畫線，把實際值都拿掉，僅用目標推估降幅來畫，所以在線段上會比較接近這樣
   > ![中國鋼鐵淨零承諾與排放量變化趨勢](https://user-images.githubusercontent.com/68453922/185585293-3fdc208f-5019-429d-811a-379796890a96.png)
   - 原本虹文是說只保留各階段目標的點就好，但考量到這樣在圖表判讀上實在很難懂（除非要從折線改為散布圖），所以還是先以折線圖的畫法來處理。
   - 工作項目：移除目標圖表上的實際值（2013～2020的盤查排放），將目標值的線段改為從2019直接往下降到第一個目標年。
   - 我這邊另外請Kelvin畫看看，如果是公司名加上點點的散布圖會長怎樣。
   - 可能接近這樣[預想](https://docs.google.com/spreadsheets/d/e/2PACX-1vQAlorxEbPJeBIaqY2jTvYiMKJoBFBysA2VHdJY_jYO3KBWhHe6pN86-TQRk7T24en2F6C4MJ5dlcEJ/pubchart?oid=1535035249&format=interactive)
4.  [ ] 針對沒有目標的產業，圖表作微調（需畫圖）
   - 目前有看到[部分產業](https://thaubing-esg.gcaa.org.tw/net-zero/02)下的公司是完全沒有提出目標的，針對這些產業，希望可以在目標這張做點調整。
   - 調整方式：圖表透明化，壓上［尚無目標］來做處理
   - 這個部分優先順位最後，可以等Kelvin圖畫好再調整。（不用趕在21日中午）

### 說明／補充／備註
如果有需要Kelvin協助畫圖的，我這邊再跟他說

**Comment by ddio** [comment]
目標圖變這樣～ @qyke 我不確定票裡有問題的截圖，是哪個產業，所以無法驗證。如果還有問題，再跟我說有問題的連結，感謝。

![Screenshot 2022-08-21 at 12-40-34 ESG 檢測儀：我們與永續轉型的距離 ESG 檢測儀](https://user-images.githubusercontent.com/271157/185776296-bc7b5906-8695-47f6-8427-f65bc503a360.png)
