### ISSUE TITLE
公司個別頁面，圖表調整查修

### ISSUE THREAD

**Issue by qyke** [gcaa-org-tw/thaubing-esg#166]
### 問題描述

1. 圖表標題修正 >> ［企業溫室氣體年排放量趨勢與減碳目標］
![image](https://user-images.githubusercontent.com/68453922/185920063-827ecaf6-cf10-42f4-9238-d693a45a5e0b.png)
2. [南亞](https://thaubing-esg.gcaa.org.tw/company/75370905/)的BAU線段看起來跑掉了，沒有從2020年開始，目前不確定是否只有南亞有問題，再請ddio確認資料。
3. 圖例需補上
需要有 BAU 線、減碳目標（若有）、IPCC、PNNL（後兩者現在已經有了）
線段名稱 BAU >> ［排放趨勢］／減碳目標 >> ［減碳目標］
4. 說明的部分我們直接編輯HackMD，感謝

目前看到的是這幾個項目需要修正，再麻煩你了～

**Comment by ddio** [comment]
修完了～半小時候更新～
