### ISSUE TITLE
[金融保險業]報告書資料匯入資料庫

### ISSUE THREAD

**Issue by qyke** [gcaa-org-tw/thaubing-esg#172]
### 工作項目
拖了很久，終於把資料整理好了。
這次的資料表將環境、社會、治理分成三張表，之後也會把其他業別既有的資料也調整成這份的格式。
之後也會把工作表的名稱統一為以下
CSR報告書資料清單-西元年（報告年度）_產業別代碼_產業別名稱
整理後會變成每個年度、每個產業都是獨立的資料表，不知道對於ddio這邊工作會不會造成很大影響？
再麻煩ddio協助調整匯入的程式碼。

資料集：[這邊](https://docs.google.com/spreadsheets/d/1RqF5MSQtICo4VV1XDwnQzh54Tl8siICT4uNV-X_Hkus/edit?usp=sharing)

- [ ] 資料表欄位確認無誤
- [ ] 調整程式碼
- [ ] 匯入資料

### 說明／補充／備註
也許可以在這邊討論一下資料表的格式？

**Comment by ddio** [comment]
@qyke  ，資料格式沒問題，對現在的程式來說，只要欄位名稱對得起來就好，檔名、在哪個頁籤影響不大。

但考量到後續資料會越來越複雜，因為資料量三個維度（公司、抓取欄位、年份）成長，等這週工作完成後，我們來對一次長期需求好了？主要會想知道，綠盟的每個人，會想要怎麼增修、使用這批資料。

**Comment by ddio** [comment]
@qyke ，對了，如果其他產業的資料，要將資料表合併成三個的話，記得跟我說一聲。因為程式需要知道，哪種資料，要去哪個資料表拿。

**Comment by ddio** [comment]
@qyke ,

金融保險業已更新～
https://thaubing-esg.gcaa.org.tw/industry/17
