### ISSUE TITLE
[ESG資料庫]企業淨零承諾欄位新增

### ISSUE THREAD

**Issue by qyke** [gcaa-org-tw/thaubing-esg#181]
### 工作項目
先前有請書榕協助將企業的淨零承諾資訊爬下來，須將這個資料放上ESG檢測儀。
資料放置位置：溫室氣體排放 >> 碳密集度｜**溫室氣體排放及減量資訊**｜碳定價

- [ ] 綠盟確認資訊內容無誤
- [ ] 開設欄位
- [ ] 匯入資訊

### 技能需求
無

### 說明／補充／備註
資訊內容需再做整理，連結後補

**Comment by ddio** [comment]
@qyke ，這題因為要整合新的 csv ，得花點時間，我週末或下週一處理呦～

**Comment by ddio** [comment]
@qyke , 這張票也做完囉～沒問題的話再幫我關掉～

https://thaubing-esg.gcaa.org.tw/industry/03?year=2021
