### ISSUE TITLE
溫室氣體排放及減量資訊_內容新增與欄位名稱調整

### ISSUE THREAD

**Issue by qyke** [gcaa-org-tw/thaubing-esg#191]
### 工作項目
先前有請ddio協助開了[溫室氣體排放及減量資訊]的欄位，但目前還沒有值。
綠盟有將資料整理過了，是乾淨的文字資料，要麻煩你新增。
因為資料的內容有做整理，所以欄位名稱也要修正。
整理後的判讀資訊我們會獨立放一個欄位，這個部分則要麻煩ddio再加開一個欄位在［溫室氣體排放及減量資訊］之後

- [ ] 更改［溫室氣體排放及減量資訊］欄位名稱為［溫室氣體減量目標說明］
- [ ] 新增一個欄位［溫室氣體減量承諾］
- [ ] 匯入資料[上市公司溫室氣體減量目標整理](https://docs.google.com/spreadsheets/d/1cUlaG2vLJst5ZGF4RB2om2-HiIRfamFhklnXF1KJ9B0/edit?usp=sharing)
- [ ] 匯入資料[上櫃公司溫室氣體減量目標整理](https://docs.google.com/spreadsheets/d/105KKLY68w0KECJ9QEfHKjvDl6ZdoVf8Rbe4vS8JpERE/edit?usp=sharing)
上面兩份資料的欄位名稱都已修正為與檢測儀符合。

因為這些資料不是來自於CSR報告書，所以兩個欄位不用標上C

**Comment by ddio** [comment]
done~~
