### ISSUE TITLE
環保署開放資料－列管基本資料、排放資料、違規裁罰紀錄

### ISSUE THREAD

**Issue by chengh42** [gcaa-org-tw/thaubing-esg#3]
### 資料清單

- [ ] [環境保護許可管理系統(暨解除列管)對象基本資料](https://data.epa.gov.tw/dataset/ems_s_01)（alt source: [data.gov.tw](https://data.gov.tw/dataset/118447)）
包含空、水、廢、土污染列管事業單位的所有基本資料。
- [ ] [列管事業污染源裁處資料](https://data.epa.gov.tw/dataset/ems_p_46)（alt source: [data.gov.tw](https://data.gov.tw/dataset/34101)）
歷年事業單位遭裁罰的所有資料（空、水、廢、毒、土、噪音、環評）。
資料單位為工廠，須合併為公司資料呈現。（因統編資料有缺值或出入，下載後需做額外處理）
- [ ] [各工廠空氣污染物排放資料](https://data.epa.gov.tw/dataset/ems_p_08)（alt source: [data.gov.tw](https://data.gov.tw/dataset/9844)）
空氣污染列管事業單位年排放污染物資料，同年不同季度之同欄位資料可合併為年度資料。
- [ ] [溫室氣體年排放量](https://data.epa.gov.tw/dataset/ghg_p_01)（alt source: [data.gov.tw](https://data.gov.tw/dataset/16059)）
溫室氣體排放單位年排放申報資料，因核算問題，採年度更新，且最新資料為2019年。
- [ ] 列管事業單位基本資料，整併溫室氣體年排放量列管事業資訊（見下方備註說明）

串接方式：環保署API，需有金鑰。可依特定欄位排序，每次存取筆數1,000筆。
檔案格式：JSON／CSV

### 備註（資料狀況待確認）

列管事業單位的基本資料（管制編號、名稱、地址等），主要從「環境保護許可管理系統(暨解除列管)對象基本資料」資料集取得，但該資料集目前只有整合空水廢毒污染源列管對象，尚未包含溫室氣體排放的列管事業單位。詳細請見該資料集在[政府資料開放平台](https://data.gov.tw/dataset/118447)上，下方提問區環保署的回覆：

> **Re: 相關資料集之列管污染源管制編號未列於本資料集？**
>
> 感謝您關心環保事務，有關您詢問環境保護許可管理系統(暨解除列管)對象基本資料內容，經洽相關單位說明如下：
> 因「環境保護許可管理系統(暨解除列管)對象基本資料」現僅提供空水廢毒污染源列管資料，該資料集目前並無納入「溫室氣體年排放量」列管事業資訊，故部分公司資料並未收錄。
> 以上說明，環保署關心您~

**Comment by qyke** [comment]
R試抓資料

library(readxl)
library(writexl)
library(dplyr)
library(tidyr)
library(jsonlite)
library(RCurl)
library(XML)
library(httr)

setwd("C:/Users/柯乾庸/Documents/GCAA/thaubing/20210810總統盃資料預抓")

a <- 0:1000

#抓取"環境保護許可管理系統(暨解除列管)對象基本資料"
ems_s_01 <- list()
for (i in 0:325) {
  url01 <- paste0("https://data.epa.gov.tw/api/v1/ems_s_01?offset=" ,a[i], "000&limit=1000&api_key=8829d459-5d78-48c2-ad70-0da20335ddac&sort=EmsNo")
  temp01a <- fromJSON(url01)
  ems_p01a <- as.data.frame(temp01a[["records"]])
  ems_s_01 <- rbind(ems_s_01, ems_p01a)
}

#抓取"列管事業污染源裁處資料"
ems_s_46 <- list()
for (i in 0:125) {
  url46 <- paste0("https://data.epa.gov.tw/api/v1/ems_s_46?offset=" ,a[i], "000&limit=1000&api_key=8829d459-5d78-48c2-ad70-0da20335ddac&sort=EMS_NO")
  temp46a <- fromJSON(url46)
  ems_p46a <- as.data.frame(temp46a[["records"]])
  ems_s_46 <- rbind(ems_s_46, ems_p46a)
}

#抓取"溫室氣體年排放量"
ghg_p_01 <- list()
for (i in 0:3) {
  urlg01 <- paste0("https://data.epa.gov.tw/api/v1/ghg_p_01?offset=" ,a[i], "000&limit=1000&api_key=8829d459-5d78-48c2-ad70-0da20335ddac&sort=companyno")
  tempg01a <- fromJSON(urlg01)
  ems_pg01a <- as.data.frame(tempg01a[["records"]])
  ghg_p_01 <- rbind(ghg_p_01, ems_pg01a)
}

#抓取"各工廠空氣污染物排放資料"
ems_s_08 <- list()
for (i in 0:800) {
  url08 <- paste0("https://data.epa.gov.tw/api/v1/ems_s_08?offset=" ,a[i], "000&limit=1000&api_key=8829d459-5d78-48c2-ad70-0da20335ddac&sort=FacilityID")
  temp08a <- fromJSON(url08)
  ems_p08a <- as.data.frame(temp08a[["records"]])
  ems_s_08 <- rbind(ems_s_08, ems_p08a)
}

**Comment by qyke** [comment]
資料試抓
[R](https://github.com/gcaa-org-tw/thaubing-esg/blob/main/CODE.R)

**Comment by qyke** [comment]
空污排放內有缺值的部分，有以下三種情況

- 管編錯誤：10筆
- 測試值：10筆
- 基本資料中無值：7筆（多數為09.10年收錄）

**Comment by qyke** [comment]
違規裁處內有缺值的部分，有以下四種情況

- 管編錯誤：4筆
- 無管編：14筆
- 基本資料中無值：12筆
- 非八碼管編：4557（多數為營造公司，八碼列管為事業單位，十二碼列管為公司）

[比對違規裁處V基本資料缺值](https://docs.google.com/spreadsheets/d/1hfs8oxam-1s8sh4GS_ejTDpwPXURtjp3/edit?usp=sharing&ouid=100571728614628784458&rtpof=true&sd=true)

**Comment by qyke** [comment]
溫室氣體於基本資料無缺值

需先將 controlno 全部轉成大寫後，再做串接，即可避免無法對應情形。

**Comment by chengh42** [comment]
如私訊提到的，再麻煩 @qyke 整理個類似 [facility_merge.xlsx](https://drive.google.com/file/d/1nYlSeFsJaeBfT0jOi1pJzO2kYnvEmXLI/view?usp=sharing)（需要透明足跡雲端硬碟權限）格式的總覽，方便比對各資料集的差異或缺漏：

- 一頁各資料集總覽，有下面幾個資料集的名稱、資料總筆數、與基本資料對比後有不一致處的資料筆數
- 一頁基本資料，有管制編號、列管單位名稱、統一編號等等
- 一頁空氣污染物排放資料，（至少）有管制編號、與基本資料對比後是否為不一致
- 一頁溫室氣體排放資料，（至少）有管制編號、與基本資料對比後是否為不一致
- 一頁違規裁處資料，（至少）有管制編號、與基本資料對比後是否為不一致

**Comment by qyke** [comment]
更新各資料集比對落差總表

[比對環署資料落差](https://docs.google.com/spreadsheets/d/1yI8y_sgXokwCFYMtqNjtZVChy7iydvHV/edit?usp=sharing&ouid=100571728614628784458&rtpof=true&sd=true)

**Comment by chengh42** [comment]
deleted previous outdated comments
