### ISSUE TITLE
空氣污染資料分組呈現

### ISSUE THREAD

**Issue by ddio** [gcaa-org-tw/thaubing-esg#59]
### 工作項目

空氣污染物申報，我們提供了一份清單用來區分一般空氣污染物與有害空氣污染物
這個部分麻煩你將目前大表的空氣污染物申報的內容拆開依文件說明來放

詳見[指標文件](https://docs.google.com/document/d/15AXynNNSIeXZyhxqNvrVBrDvVEkuh5XIRbnBWQsR54Q/edit?fbclid=IwAR2NjA23YEIC-wcAUfQPCweBw5cdN-SXEBL-vTuvMAwjfvt-U9pFkjQYDHU)

**Comment by ddio** [comment]
@qyke ,

已更新，可以看[石化業](https://gcaa-org-tw.github.io/thaubing-esg/industry/%E7%9F%B3%E5%8C%96%E6%A5%AD)，沒問題的話，再幫我把票關掉～

**Comment by chengh42** [comment]
> 
> @chengh42 ，目前 git 裡的 `data/ems_p_08.csv` ，缺了各污染物的單位，以及 `1-1-1-三氯乙烷` ，如果有增加的話，再跟我說～

收到，我明天來看看！

**Comment by qyke** [comment]
分類表中補上 重金屬、戴奧辛 的分類，再請 @ddio  調整
