### ISSUE TITLE
更細的裁罰分類、圖表

### ISSUE THREAD

**Issue by ddio** [gcaa-org-tw/thaubing-esg#60]
### 工作項目

在裁罰部分，我們把實際造成污染的空氣、水的相關法規抓出來，這個部分要麻煩以文字內容是否包含來做判斷
要調整的呈現是個別公司的頁面，在違反環境法規的長條圖，變成堆疊長條圖，從上到下分別是

- 非實際造成污染
- 造成水污染
- 造成空氣污染

詳見[指標文件](https://docs.google.com/document/d/15AXynNNSIeXZyhxqNvrVBrDvVEkuh5XIRbnBWQsR54Q/edit?fbclid=IwAR2NjA23YEIC-wcAUfQPCweBw5cdN-SXEBL-vTuvMAwjfvt-U9pFkjQYDHU)

**Comment by ddio** [comment]
從指標文件複製來的需求：

區分實際污染與行政違規：實際造成污染之法規
以[列管事業污染源裁處資料]的[TRANSGRESS_LAW]作為判定，若裁罰法規包含實際造成污染之法規的條目，則判定為有造成污染
區分為空氣、水

改目前的長條圖呈現方式，變為堆疊長條圖（金額）
堆疊方式從上到下分別是
-非實際造成污染
-造成水污染
-造成空氣污染

圖例文字：
-因空氣污染遭裁罰金額
-因水污染遭裁罰金額
-其他違規項目金額

**Comment by ddio** [comment]
@qyke , 目前的邏輯，會讓「其他違規項目」，被當成「非實際造成污染」呦，像是：

1. 土壤及地下水污染整治法第12條第3項
2. 噪音管制法第8條第4款

**Comment by ddio** [comment]
@qyke , @chengh42 ,

因為感覺起來，裁罰的分類邏輯，有可能會持續變化，所以我把原本放在 google spreadsheet 的對照表，搬到 git 裡，方便程式運作呦～

[`data/penalty_category.csv`](https://github.com/gcaa-org-tw/thaubing-esg/blob/main/data/penalty_category.csv)

**Comment by ddio** [comment]
@qyke  已更新，可以看[台塑化](https://gcaa-org-tw.github.io/thaubing-esg/company/%E5%8F%B0%E5%A1%91)

沒其他問題的話，再幫我把這張票關掉～

**Comment by qyke** [comment]
@ddio 裁罰的分類部分，[空氣污染防制法第32條]這一條好像沒有分到。
另外，[水污染防治法第18條之一]，這條做了修正，文字直接更改為[水污染防治法第18條之1]
～
土污、噪音、廢棄物等，因為同一條法規涵蓋的面向比較廣，所以暫時還不作為區分使用。
