### ISSUE TITLE
新增同產業比較圖（含金融商品投資標的標註）：碳密集度＆能源密集度

### ISSUE THREAD

**Issue by chengh42** [gcaa-org-tw/thaubing-esg#61]
昨天跟綠盟討論後，希望可以在現有的各產業頁面上放上**同一產業中各公司的表現比較圖**，有幾點想跟Kelvin和ddio討論和請兩位幫忙：

#### 想透過比較圖達到的目的

- 讓使用者清楚看到與初步比較該產業各公司在特定指標的表現
- 看到哪些公司是哪幾項ESG金融商品的投資標的（資料在這邊：[CSR報告書資料清單-ESG名單 (google spreadsheet)](https://docs.google.com/spreadsheets/d/1jS8tjS6zoU4TYZRANSsEJM4CRlG6doJPJ1xfavMeJ64/)）

目前初步挑選**碳密集度**跟**能源密集度**兩項指標做圖。

#### 比較圖波波獸

見下方附圖（以石化業－碳密集度為例）：

- 資料排序後做成長條圖，由左至右表示**指標表現由優至劣**（碳密集度值越大，表現越差）
- 透過長條圖的顏色區分該指標表現的前／中／後段班：排名前25%為前段班，後25%為後段班
- 若該公司屬於某ESG金融商品的投資標的，則在長條圖頂端標示該商品簡稱
- 提供一個下拉式選單，讓使用者可以切換不同指標看比較結果

#### 討論

- 如何處理無資料的公司？
   - 初步想法：一樣列在圖表上，放在最右側（劣端），但不繪製長條圖，僅標註「無資料」 
- 想請 @kelvin-gosky 幫忙確認／調整版面位置／設計
- 最後請 @ddio 幫忙加進網站中

cc @qyke

---

![image](https://user-images.githubusercontent.com/44002425/140477788-2b6c6164-a496-4475-a030-bed7f345fceb.png)

<img src="https://user-images.githubusercontent.com/44002425/140476118-e2ba3da2-8766-4656-99ac-c1fe64ebc4ce.png" data-canonical-src="https://user-images.githubusercontent.com/44002425/140476118-e2ba3da2-8766-4656-99ac-c1fe64ebc4ce.png" width="60%" />

**Comment by ddio** [comment]
聊天室資訊，同步來這兒，留個紀錄～
---
因為每個產業的公司有點多（25 ~ 100 間），但又要突顯基金挑選的問題，我覺得短期（總統杯）可以像這樣。

1. 沒資料的，放在紅黃之間，因為重點要先突顯紅的（前 25%）
2. 長條圖改為水平，右側就能放各基金的標的涵蓋，方便理解「我有興趣的基金，有沒有投資表現差的公司」

![2021-11-07 16-23-44 的螢幕擷圖](https://user-images.githubusercontent.com/271157/140642266-e83b2d31-72d0-40ed-94ea-be01944103f2.png)

左上角是 tab （頁籤），可以切換看能源密集度、碳排密集度
我也覺得要從表格獨立出來，因為這裡有比較強的詮釋，圖表每欄的空間較小，比較難表達意思

**Comment by chengh42** [comment]
closing as charts were already created (beautifully)!
